-- ============================================================
-- Campaign Companion — Puzzle Vault v1
-- Five configurable puzzle engines with persistent state,
-- controller locking, live spectators, RLS, and private Realtime rooms.
--
-- Prerequisites:
--   public.campaigns
--   public.campaign_members
--   public.profiles
--   public.is_campaign_member(uuid)
--   public.is_campaign_dm(uuid)
-- ============================================================

begin;

create table if not exists public.campaign_puzzles (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  title text not null,
  description text not null default '',
  puzzle_type text not null,
  difficulty_label text not null default 'Medium',
  public_config jsonb not null default '{}'::jsonb,
  move_limit integer,
  attempt_limit integer,
  time_limit_seconds integer,
  failure_message text,
  is_visible boolean not null default false,
  status text not null default 'draft',
  current_run_id uuid,
  sort_order integer not null default 500,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaign_puzzles_type_check check (
    puzzle_type in ('rune_cipher','sliding_lock','shattered_sigil','arcane_circuit','rune_sequence')
  ),
  constraint campaign_puzzles_status_check check (
    status in ('draft','active','solved','failed','archived')
  ),
  constraint campaign_puzzles_title_check check (char_length(trim(title)) between 1 and 120),
  constraint campaign_puzzles_description_check check (char_length(description) <= 2000),
  constraint campaign_puzzles_failure_message_check check (failure_message is null or char_length(failure_message) <= 500),
  constraint campaign_puzzles_move_limit_check check (move_limit is null or move_limit between 1 and 999),
  constraint campaign_puzzles_attempt_limit_check check (attempt_limit is null or attempt_limit between 1 and 999),
  constraint campaign_puzzles_time_limit_check check (time_limit_seconds is null or time_limit_seconds between 10 and 86400)
);

create table if not exists public.campaign_puzzle_secrets (
  puzzle_id uuid primary key references public.campaign_puzzles(id) on delete cascade,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  secret_config jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.campaign_puzzle_runs (
  id uuid primary key default gen_random_uuid(),
  puzzle_id uuid not null references public.campaign_puzzles(id) on delete cascade,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  status text not null default 'active',
  state jsonb not null default '{}'::jsonb,
  move_count integer not null default 0,
  attempt_count integer not null default 0,
  started_at timestamptz not null default now(),
  deadline_at timestamptz,
  solved_at timestamptz,
  failed_at timestamptz,
  controller_user_id uuid references auth.users(id) on delete set null,
  controller_name text,
  control_expires_at timestamptz,
  version integer not null default 1,
  updated_at timestamptz not null default now(),
  constraint campaign_puzzle_runs_status_check check (
    status in ('active','solved','failed','superseded')
  ),
  constraint campaign_puzzle_runs_counts_check check (move_count >= 0 and attempt_count >= 0)
);

create table if not exists public.campaign_puzzle_moves (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.campaign_puzzle_runs(id) on delete cascade,
  puzzle_id uuid not null references public.campaign_puzzles(id) on delete cascade,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  move_number integer not null,
  action jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (run_id, move_number)
);

create index if not exists campaign_puzzles_campaign_idx
  on public.campaign_puzzles(campaign_id, status, is_visible, sort_order);
create index if not exists campaign_puzzle_runs_campaign_idx
  on public.campaign_puzzle_runs(campaign_id, puzzle_id, started_at desc);
create index if not exists campaign_puzzle_moves_run_idx
  on public.campaign_puzzle_moves(run_id, move_number);

-- Add the circular current-run foreign key only after both tables exist.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'campaign_puzzles_current_run_id_fkey'
  ) then
    alter table public.campaign_puzzles
      add constraint campaign_puzzles_current_run_id_fkey
      foreign key (current_run_id)
      references public.campaign_puzzle_runs(id)
      on delete set null;
  end if;
end;
$$;

create or replace function public.set_campaign_puzzle_audit_fields()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := coalesce(new.created_at, now());
    new.created_by := coalesce(new.created_by, auth.uid());
  end if;
  new.updated_at := now();
  new.updated_by := coalesce(auth.uid(), new.updated_by);
  return new;
end;
$$;

drop trigger if exists campaign_puzzles_set_audit_fields on public.campaign_puzzles;
create trigger campaign_puzzles_set_audit_fields
before insert or update on public.campaign_puzzles
for each row execute function public.set_campaign_puzzle_audit_fields();

create or replace function public.can_view_campaign_puzzle(target_puzzle_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.campaign_puzzles p
    where p.id = target_puzzle_id
      and (
        public.is_campaign_dm(p.campaign_id)
        or (
          public.is_campaign_member(p.campaign_id)
          and p.is_visible = true
          and p.status in ('active','solved','failed')
        )
      )
  );
$$;

create or replace function public.can_manage_campaign_puzzle(target_puzzle_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.campaign_puzzles p
    where p.id = target_puzzle_id
      and public.is_campaign_dm(p.campaign_id)
  );
$$;

create or replace function public.can_access_campaign_puzzle_topic(target_topic text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_run_id uuid;
  v_puzzle_id uuid;
begin
  if target_topic is null or target_topic !~ '^campaign-puzzle:[0-9a-fA-F-]{36}$' then
    return false;
  end if;

  begin
    v_run_id := split_part(target_topic, ':', 2)::uuid;
  exception when others then
    return false;
  end;

  select r.puzzle_id into v_puzzle_id
  from public.campaign_puzzle_runs r
  where r.id = v_run_id;

  if v_puzzle_id is null then
    return false;
  end if;

  return public.can_view_campaign_puzzle(v_puzzle_id);
end;
$$;

alter table public.campaign_puzzles enable row level security;
alter table public.campaign_puzzle_secrets enable row level security;
alter table public.campaign_puzzle_runs enable row level security;
alter table public.campaign_puzzle_moves enable row level security;

revoke all on public.campaign_puzzles from anon;
revoke all on public.campaign_puzzle_secrets from anon;
revoke all on public.campaign_puzzle_runs from anon;
revoke all on public.campaign_puzzle_moves from anon;

revoke insert, update, delete on public.campaign_puzzles from authenticated;
revoke insert, update, delete on public.campaign_puzzle_secrets from authenticated;
revoke insert, update, delete on public.campaign_puzzle_runs from authenticated;
revoke insert, update, delete on public.campaign_puzzle_moves from authenticated;

grant select on public.campaign_puzzles to authenticated;
grant select on public.campaign_puzzle_runs to authenticated;
grant select on public.campaign_puzzle_moves to authenticated;
grant select on public.campaign_puzzle_secrets to authenticated;

drop policy if exists "Puzzle members can read visible puzzles" on public.campaign_puzzles;
create policy "Puzzle members can read visible puzzles"
on public.campaign_puzzles for select to authenticated
using (
  public.is_campaign_dm(campaign_id)
  or (
    public.is_campaign_member(campaign_id)
    and is_visible = true
    and status in ('active','solved','failed')
  )
);

drop policy if exists "Puzzle DMs can read secrets" on public.campaign_puzzle_secrets;
create policy "Puzzle DMs can read secrets"
on public.campaign_puzzle_secrets for select to authenticated
using (public.is_campaign_dm(campaign_id));

drop policy if exists "Puzzle members can read runs" on public.campaign_puzzle_runs;
create policy "Puzzle members can read runs"
on public.campaign_puzzle_runs for select to authenticated
using (public.can_view_campaign_puzzle(puzzle_id));

drop policy if exists "Puzzle members can read moves" on public.campaign_puzzle_moves;
create policy "Puzzle members can read moves"
on public.campaign_puzzle_moves for select to authenticated
using (public.can_view_campaign_puzzle(puzzle_id));

-- Build the initial public run state from a puzzle's public configuration.
create or replace function public.build_campaign_puzzle_initial_state(
  p_type text,
  p_public_config jsonb
)
returns jsonb
language plpgsql
immutable
set search_path = public
as $$
begin
  case p_type
    when 'rune_cipher' then
      return jsonb_build_object('guesses', '[]'::jsonb);
    when 'sliding_lock' then
      return jsonb_build_object('blocks', coalesce(p_public_config->'blocks', '[]'::jsonb), 'selected', null);
    when 'shattered_sigil' then
      return jsonb_build_object('order', coalesce(p_public_config->'initial_order', '[]'::jsonb), 'selected', null);
    when 'arcane_circuit' then
      return jsonb_build_object('rotations', coalesce(p_public_config->'initial_rotations', '[]'::jsonb));
    when 'rune_sequence' then
      return jsonb_build_object('level', 1, 'last_feedback', null, 'reveals', 0);
    else
      raise exception 'Unsupported puzzle type: %', p_type;
  end case;
end;
$$;

-- Rotate a N/E/S/W bit mask clockwise. Used server-side so symmetric
-- circuit pieces (for example a straight line rotated 180°) count as solved.
create or replace function public.rotate_campaign_puzzle_mask(
  p_mask integer,
  p_rotation integer
)
returns integer
language plpgsql
immutable
set search_path = public
as $$
declare
  v_value integer := p_mask;
  v_steps integer := ((coalesce(p_rotation,0) % 4) + 4) % 4;
  v_n integer;
  v_e integer;
  v_s integer;
  v_w integer;
  i integer;
begin
  if v_steps > 0 then
    for i in 1..v_steps loop
      v_n := v_value & 1;
      v_e := v_value & 2;
      v_s := v_value & 4;
      v_w := v_value & 8;
      v_value := (case when v_n <> 0 then 2 else 0 end)
               | (case when v_e <> 0 then 4 else 0 end)
               | (case when v_s <> 0 then 8 else 0 end)
               | (case when v_w <> 0 then 1 else 0 end);
    end loop;
  end if;
  return v_value;
end;
$$;

-- DM-only create/update. Secret config is kept in a separate RLS-protected table.
create or replace function public.save_campaign_puzzle(
  p_campaign_slug text,
  p_puzzle_id uuid,
  p_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id uuid;
  v_puzzle_id uuid;
  v_type text;
  v_title text;
  v_description text;
  v_difficulty text;
  v_move_limit integer;
  v_attempt_limit integer;
  v_time_limit integer;
  v_failure_message text;
  v_public_config jsonb;
  v_secret_config jsonb;
  v_sort_order integer;
begin
  select c.id into v_campaign_id
  from public.campaigns c
  where c.slug = lower(trim(p_campaign_slug)) and c.is_active = true;

  if v_campaign_id is null then
    raise exception 'Campaign not found or inactive.';
  end if;
  if not public.is_campaign_dm(v_campaign_id) then
    raise exception 'Only the campaign Game Master may configure puzzles.';
  end if;

  v_type := trim(coalesce(p_payload->>'puzzle_type', ''));
  v_title := trim(coalesce(p_payload->>'title', ''));
  v_description := coalesce(p_payload->>'description', '');
  v_difficulty := trim(coalesce(p_payload->>'difficulty_label', 'Medium'));
  v_move_limit := nullif(p_payload->>'move_limit', '')::integer;
  v_attempt_limit := nullif(p_payload->>'attempt_limit', '')::integer;
  v_time_limit := nullif(p_payload->>'time_limit_seconds', '')::integer;
  v_failure_message := nullif(p_payload->>'failure_message', '');
  v_public_config := coalesce(p_payload->'public_config', '{}'::jsonb);
  v_secret_config := coalesce(p_payload->'secret_config', '{}'::jsonb);
  v_sort_order := coalesce((p_payload->>'sort_order')::integer, 500);

  if v_type not in ('rune_cipher','sliding_lock','shattered_sigil','arcane_circuit','rune_sequence') then
    raise exception 'Unsupported puzzle type.';
  end if;
  if char_length(v_title) < 1 or char_length(v_title) > 120 then
    raise exception 'Puzzle title must contain 1-120 characters.';
  end if;
  if char_length(v_description) > 2000 then
    raise exception 'Puzzle description is too long.';
  end if;
  if v_move_limit is not null and (v_move_limit < 1 or v_move_limit > 999) then
    raise exception 'Move limit must be between 1 and 999.';
  end if;
  if v_attempt_limit is not null and (v_attempt_limit < 1 or v_attempt_limit > 999) then
    raise exception 'Attempt limit must be between 1 and 999.';
  end if;
  if v_time_limit is not null and (v_time_limit < 10 or v_time_limit > 86400) then
    raise exception 'Time limit must be between 10 and 86400 seconds.';
  end if;

  if p_puzzle_id is null then
    insert into public.campaign_puzzles (
      campaign_id, title, description, puzzle_type, difficulty_label,
      public_config, move_limit, attempt_limit, time_limit_seconds,
      failure_message, is_visible, status, sort_order, created_by, updated_by
    ) values (
      v_campaign_id, v_title, v_description, v_type, v_difficulty,
      v_public_config, v_move_limit, v_attempt_limit, v_time_limit,
      v_failure_message, false, 'draft', v_sort_order, auth.uid(), auth.uid()
    ) returning id into v_puzzle_id;
  else
    if not exists (
      select 1 from public.campaign_puzzles p
      where p.id = p_puzzle_id and p.campaign_id = v_campaign_id
    ) then
      raise exception 'Puzzle not found in this campaign.';
    end if;
    v_puzzle_id := p_puzzle_id;
    update public.campaign_puzzles
    set title = v_title,
        description = v_description,
        puzzle_type = v_type,
        difficulty_label = v_difficulty,
        public_config = v_public_config,
        move_limit = v_move_limit,
        attempt_limit = v_attempt_limit,
        time_limit_seconds = v_time_limit,
        failure_message = v_failure_message,
        sort_order = v_sort_order,
        updated_by = auth.uid()
    where id = v_puzzle_id;
  end if;

  insert into public.campaign_puzzle_secrets (
    puzzle_id, campaign_id, secret_config, updated_by, updated_at
  ) values (
    v_puzzle_id, v_campaign_id, v_secret_config, auth.uid(), now()
  )
  on conflict (puzzle_id) do update
  set secret_config = excluded.secret_config,
      updated_by = excluded.updated_by,
      updated_at = now();

  return v_puzzle_id;
end;
$$;

create or replace function public.start_campaign_puzzle(
  p_puzzle_id uuid,
  p_make_visible boolean default true
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_puzzle public.campaign_puzzles%rowtype;
  v_run_id uuid;
  v_state jsonb;
  v_deadline timestamptz;
begin
  select * into v_puzzle
  from public.campaign_puzzles
  where id = p_puzzle_id
  for update;

  if v_puzzle.id is null then raise exception 'Puzzle not found.'; end if;
  if not public.is_campaign_dm(v_puzzle.campaign_id) then
    raise exception 'Only the campaign Game Master may start puzzles.';
  end if;
  if v_puzzle.status = 'archived' then
    raise exception 'Archived puzzles cannot be started.';
  end if;

  if v_puzzle.current_run_id is not null then
    update public.campaign_puzzle_runs
    set status = case when status = 'active' then 'superseded' else status end,
        controller_user_id = null,
        controller_name = null,
        control_expires_at = null,
        updated_at = now()
    where id = v_puzzle.current_run_id;
  end if;

  v_state := public.build_campaign_puzzle_initial_state(v_puzzle.puzzle_type, v_puzzle.public_config);
  v_deadline := case
    when v_puzzle.time_limit_seconds is null then null
    else now() + make_interval(secs => v_puzzle.time_limit_seconds)
  end;

  insert into public.campaign_puzzle_runs (
    puzzle_id, campaign_id, status, state, move_count, attempt_count,
    started_at, deadline_at, version, updated_at
  ) values (
    v_puzzle.id, v_puzzle.campaign_id, 'active', v_state, 0, 0,
    now(), v_deadline, 1, now()
  ) returning id into v_run_id;

  update public.campaign_puzzles
  set current_run_id = v_run_id,
      status = 'active',
      is_visible = p_make_visible,
      updated_by = auth.uid()
  where id = v_puzzle.id;

  return v_run_id;
end;
$$;

create or replace function public.set_campaign_puzzle_visibility(
  p_puzzle_id uuid,
  p_visible boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id uuid;
begin
  select campaign_id into v_campaign_id from public.campaign_puzzles where id = p_puzzle_id;
  if v_campaign_id is null then raise exception 'Puzzle not found.'; end if;
  if not public.is_campaign_dm(v_campaign_id) then raise exception 'Game Master access required.'; end if;
  update public.campaign_puzzles
  set is_visible = p_visible, updated_by = auth.uid()
  where id = p_puzzle_id;
end;
$$;

create or replace function public.archive_campaign_puzzle(p_puzzle_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id uuid;
  v_run_id uuid;
begin
  select campaign_id, current_run_id into v_campaign_id, v_run_id
  from public.campaign_puzzles where id = p_puzzle_id for update;
  if v_campaign_id is null then raise exception 'Puzzle not found.'; end if;
  if not public.is_campaign_dm(v_campaign_id) then raise exception 'Game Master access required.'; end if;
  if v_run_id is not null then
    update public.campaign_puzzle_runs
    set status = case when status='active' then 'superseded' else status end,
        controller_user_id = null, controller_name = null, control_expires_at = null,
        updated_at = now()
    where id = v_run_id;
  end if;
  update public.campaign_puzzles
  set status='archived', is_visible=false, updated_by=auth.uid()
  where id=p_puzzle_id;
end;
$$;

create or replace function public.take_campaign_puzzle_control(p_run_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.campaign_puzzle_runs%rowtype;
  v_name text;
  v_is_dm boolean;
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;

  select * into v_run from public.campaign_puzzle_runs where id=p_run_id for update;
  if v_run.id is null then raise exception 'Puzzle run not found.'; end if;
  if not public.can_view_campaign_puzzle(v_run.puzzle_id) then raise exception 'Puzzle access denied.'; end if;
  if v_run.status <> 'active' then return false; end if;

  v_is_dm := public.is_campaign_dm(v_run.campaign_id);
  if v_run.controller_user_id is not null
     and v_run.controller_user_id <> auth.uid()
     and coalesce(v_run.control_expires_at, '-infinity'::timestamptz) > now()
     and not v_is_dm then
    return false;
  end if;

  select nullif(trim(p.display_name),'') into v_name
  from public.profiles p where p.id=auth.uid();

  update public.campaign_puzzle_runs
  set controller_user_id=auth.uid(),
      controller_name=coalesce(v_name,'Campaign member'),
      control_expires_at=now()+interval '45 seconds',
      updated_at=now()
  where id=p_run_id;
  return true;
end;
$$;

create or replace function public.heartbeat_campaign_puzzle_control(p_run_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.campaign_puzzle_runs
  set control_expires_at=now()+interval '45 seconds', updated_at=now()
  where id=p_run_id
    and status='active'
    and controller_user_id=auth.uid();
  return found;
end;
$$;

create or replace function public.release_campaign_puzzle_control(p_run_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id uuid;
  v_controller uuid;
begin
  select campaign_id, controller_user_id into v_campaign_id, v_controller
  from public.campaign_puzzle_runs where id=p_run_id;
  if v_campaign_id is null then return false; end if;
  if v_controller <> auth.uid() and not public.is_campaign_dm(v_campaign_id) then return false; end if;
  update public.campaign_puzzle_runs
  set controller_user_id=null, controller_name=null, control_expires_at=null, updated_at=now()
  where id=p_run_id;
  return true;
end;
$$;

create or replace function public.expire_campaign_puzzle_run(p_run_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.campaign_puzzle_runs%rowtype;
begin
  select * into v_run from public.campaign_puzzle_runs where id=p_run_id for update;
  if v_run.id is null then return false; end if;
  if not public.can_view_campaign_puzzle(v_run.puzzle_id) then return false; end if;
  if v_run.status='active' and v_run.deadline_at is not null and v_run.deadline_at <= now() then
    update public.campaign_puzzle_runs
    set status='failed', failed_at=now(), controller_user_id=null, controller_name=null,
        control_expires_at=null, version=version+1, updated_at=now()
    where id=p_run_id;
    update public.campaign_puzzles set status='failed', updated_at=now() where id=v_run.puzzle_id;
    return true;
  end if;
  return false;
end;
$$;

-- Returns only the currently required memory prefix, and only to the controller or DM.
create or replace function public.reveal_campaign_puzzle_sequence(p_run_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.campaign_puzzle_runs%rowtype;
  v_puzzle public.campaign_puzzles%rowtype;
  v_secret jsonb;
  v_sequence text[];
  v_level integer;
  v_base integer;
  v_needed integer;
  v_result text[];
  v_reveal_limit integer;
  v_reveals integer;
begin
  select * into v_run from public.campaign_puzzle_runs where id=p_run_id for update;
  if v_run.id is null or v_run.status <> 'active' then raise exception 'Puzzle run is not active.'; end if;
  select * into v_puzzle from public.campaign_puzzles where id=v_run.puzzle_id;
  if v_puzzle.puzzle_type <> 'rune_sequence' then raise exception 'This puzzle has no memory sequence.'; end if;
  if v_run.controller_user_id <> auth.uid() and not public.is_campaign_dm(v_run.campaign_id) then
    raise exception 'Take control before revealing the sequence.';
  end if;
  select secret_config into v_secret from public.campaign_puzzle_secrets where puzzle_id=v_puzzle.id;
  select array_agg(value order by ordinality)
  into v_sequence
  from jsonb_array_elements_text(coalesce(v_secret->'sequence','[]'::jsonb)) with ordinality as s(value, ordinality);
  v_level := greatest(1, coalesce((v_run.state->>'level')::integer,1));
  v_base := greatest(1, coalesce((v_puzzle.public_config->>'base_length')::integer,3));
  v_needed := v_base + v_level - 1;
  v_reveal_limit := nullif(v_puzzle.public_config->>'reveal_limit','')::integer;
  v_reveals := coalesce((v_run.state->>'reveals')::integer,0);
  if v_reveal_limit is not null and v_reveals >= v_reveal_limit then
    raise exception 'No rune echoes remain for this puzzle run.';
  end if;
  v_result := v_sequence[1:v_needed];
  update public.campaign_puzzle_runs
  set state=jsonb_set(state,'{reveals}',to_jsonb(v_reveals+1),true),
      version=version+1, updated_at=now()
  where id=p_run_id;
  return to_jsonb(coalesce(v_result,'{}'::text[]));
end;
$$;

-- Main player action RPC. The database is authoritative and never exposes secret_config.
create or replace function public.apply_campaign_puzzle_action(
  p_run_id uuid,
  p_action jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.campaign_puzzle_runs%rowtype;
  v_puzzle public.campaign_puzzles%rowtype;
  v_secret jsonb;
  v_action_type text;
  v_state jsonb;
  v_new_state jsonb;
  v_new_move_count integer;
  v_new_attempt_count integer;
  v_solved boolean := false;
  v_failed boolean := false;
  v_move_number integer;

  -- Cipher
  v_solution text[];
  v_guess text[];
  v_code_length integer;
  v_exact integer := 0;
  v_misplaced integer := 0;
  v_sol_used boolean[];
  v_guess_used boolean[];
  v_runes text[];
  v_allow_repeats boolean;
  i integer;
  j integer;

  -- Sliding lock
  v_blocks jsonb;
  v_block jsonb;
  v_other jsonb;
  v_block_id text;
  v_direction text;
  v_axis text;
  v_x integer;
  v_y integer;
  v_w integer;
  v_h integer;
  v_nx integer;
  v_ny integer;
  v_board_w integer;
  v_board_h integer;
  v_target_id text;
  v_target jsonb;

  -- Arrays
  v_values text[];
  v_target_values text[];
  v_from integer;
  v_to integer;
  v_size integer;
  v_tmp text;
  v_rotations integer[];
  v_masks integer[];
  v_target_masks integer[];
  v_index integer;
  v_delta integer;

  -- Sequence
  v_level integer;
  v_base integer;
  v_max_level integer;
  v_needed integer;
  v_reset_on_miss boolean;
  v_prefix text[];
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  select * into v_run from public.campaign_puzzle_runs where id=p_run_id for update;
  if v_run.id is null then raise exception 'Puzzle run not found.'; end if;
  select * into v_puzzle from public.campaign_puzzles where id=v_run.puzzle_id;
  if not public.can_view_campaign_puzzle(v_puzzle.id) then raise exception 'Puzzle access denied.'; end if;
  if v_run.status <> 'active' then raise exception 'This puzzle run is no longer active.'; end if;

  if v_run.deadline_at is not null and v_run.deadline_at <= now() then
    update public.campaign_puzzle_runs
    set status='failed', failed_at=now(), controller_user_id=null, controller_name=null,
        control_expires_at=null, version=version+1, updated_at=now()
    where id=v_run.id;
    update public.campaign_puzzles set status='failed', updated_at=now() where id=v_puzzle.id;
    raise exception 'The puzzle timer has expired.';
  end if;

  if v_run.controller_user_id <> auth.uid()
     or coalesce(v_run.control_expires_at,'-infinity'::timestamptz) <= now() then
    raise exception 'Take control of the puzzle before making a move.';
  end if;

  v_action_type := coalesce(p_action->>'type','');
  v_state := v_run.state;
  v_new_state := v_state;
  v_new_move_count := v_run.move_count;
  v_new_attempt_count := v_run.attempt_count;

  select secret_config into v_secret
  from public.campaign_puzzle_secrets where puzzle_id=v_puzzle.id;
  v_secret := coalesce(v_secret,'{}'::jsonb);

  if v_puzzle.puzzle_type = 'rune_cipher' then
    if v_action_type <> 'cipher_guess' then raise exception 'Invalid Rune Cipher action.'; end if;
    select array_agg(value order by ordinality) into v_solution
      from jsonb_array_elements_text(coalesce(v_secret->'solution','[]'::jsonb)) with ordinality as s(value,ordinality);
    select array_agg(value order by ordinality) into v_guess
      from jsonb_array_elements_text(coalesce(p_action->'guess','[]'::jsonb)) with ordinality as g(value,ordinality);
    v_code_length := coalesce((v_puzzle.public_config->>'code_length')::integer, cardinality(v_solution));
    if coalesce(cardinality(v_guess),0) <> v_code_length
       or coalesce(cardinality(v_solution),0) <> v_code_length then
      raise exception 'Rune guess or configured solution has an invalid length.';
    end if;
    select array_agg(value order by ordinality) into v_runes
      from jsonb_array_elements_text(coalesce(v_puzzle.public_config->'runes','[]'::jsonb)) with ordinality as r(value,ordinality);
    for i in 1..v_code_length loop
      if v_runes is null or not (v_guess[i] = any(v_runes)) then
        raise exception 'The guess contains a rune that is not part of this cipher.';
      end if;
    end loop;
    v_allow_repeats := coalesce((v_puzzle.public_config->>'allow_repeats')::boolean,true);
    if not v_allow_repeats and (
      select count(distinct rune) from unnest(v_guess) as guessed(rune)
    ) <> cardinality(v_guess) then
      raise exception 'This cipher does not allow repeated runes.';
    end if;
    v_sol_used := array_fill(false, array[v_code_length]);
    v_guess_used := array_fill(false, array[v_code_length]);
    for i in 1..v_code_length loop
      if v_guess[i]=v_solution[i] then
        v_exact:=v_exact+1; v_sol_used[i]:=true; v_guess_used[i]:=true;
      end if;
    end loop;
    for i in 1..v_code_length loop
      if not v_guess_used[i] then
        for j in 1..v_code_length loop
          if not v_sol_used[j] and v_guess[i]=v_solution[j] then
            v_misplaced:=v_misplaced+1; v_sol_used[j]:=true; exit;
          end if;
        end loop;
      end if;
    end loop;
    v_new_state := jsonb_set(
      v_state,
      '{guesses}',
      coalesce(v_state->'guesses','[]'::jsonb) || jsonb_build_array(
        jsonb_build_object('guess',to_jsonb(v_guess),'exact',v_exact,'misplaced',v_misplaced)
      ),
      true
    );
    v_new_move_count := v_new_move_count + 1;
    v_new_attempt_count := v_new_attempt_count + 1;
    v_solved := v_exact = v_code_length;

  elsif v_puzzle.puzzle_type = 'sliding_lock' then
    if v_action_type <> 'slide' then raise exception 'Invalid Sliding Lock action.'; end if;
    v_block_id := p_action->>'block_id';
    v_direction := p_action->>'direction';
    v_blocks := coalesce(v_state->'blocks','[]'::jsonb);
    select b into v_block from jsonb_array_elements(v_blocks) b where b->>'id'=v_block_id limit 1;
    if v_block is null then raise exception 'Unknown lock block.'; end if;
    v_axis:=v_block->>'axis'; v_x:=(v_block->>'x')::integer; v_y:=(v_block->>'y')::integer;
    v_w:=(v_block->>'w')::integer; v_h:=(v_block->>'h')::integer; v_nx:=v_x; v_ny:=v_y;
    if v_direction='left' and v_axis='h' then v_nx:=v_x-1;
    elsif v_direction='right' and v_axis='h' then v_nx:=v_x+1;
    elsif v_direction='up' and v_axis='v' then v_ny:=v_y-1;
    elsif v_direction='down' and v_axis='v' then v_ny:=v_y+1;
    else raise exception 'That block cannot move in this direction.';
    end if;
    v_board_w:=coalesce((v_puzzle.public_config->>'width')::integer,6);
    v_board_h:=coalesce((v_puzzle.public_config->>'height')::integer,6);
    if v_nx<0 or v_ny<0 or v_nx+v_w>v_board_w or v_ny+v_h>v_board_h then
      raise exception 'The block would leave the lock frame.';
    end if;
    for v_other in select value from jsonb_array_elements(v_blocks) where value->>'id'<>v_block_id loop
      if v_nx < (v_other->>'x')::integer + (v_other->>'w')::integer
         and v_nx + v_w > (v_other->>'x')::integer
         and v_ny < (v_other->>'y')::integer + (v_other->>'h')::integer
         and v_ny + v_h > (v_other->>'y')::integer then
        raise exception 'Another ward blocks that movement.';
      end if;
    end loop;
    select jsonb_agg(
      case when value->>'id'=v_block_id then
        jsonb_set(jsonb_set(value,'{x}',to_jsonb(v_nx),true),'{y}',to_jsonb(v_ny),true)
      else value end
    ) into v_blocks from jsonb_array_elements(v_blocks);
    v_new_state:=jsonb_set(v_state,'{blocks}',coalesce(v_blocks,'[]'::jsonb),true);
    v_new_move_count:=v_new_move_count+1;
    v_target_id:=coalesce(v_puzzle.public_config->>'target_block_id','A');
    select b into v_target from jsonb_array_elements(v_blocks) b where b->>'id'=v_target_id limit 1;
    v_solved := v_target is not null
      and (v_target->>'x')::integer + (v_target->>'w')::integer = v_board_w
      and (v_target->>'y')::integer = coalesce((v_puzzle.public_config->>'exit_row')::integer,(v_target->>'y')::integer);

  elsif v_puzzle.puzzle_type = 'shattered_sigil' then
    if v_action_type <> 'swap' then raise exception 'Invalid Shattered Sigil action.'; end if;
    select array_agg(value order by ordinality) into v_values
      from jsonb_array_elements_text(coalesce(v_state->'order','[]'::jsonb)) with ordinality as s(value,ordinality);
    select array_agg(value order by ordinality) into v_target_values
      from jsonb_array_elements_text(coalesce(v_secret->'target_order','[]'::jsonb)) with ordinality as s(value,ordinality);
    v_size:=coalesce((v_puzzle.public_config->>'size')::integer,3);
    if coalesce(cardinality(v_values),0) = 0
       or coalesce(cardinality(v_target_values),0) <> cardinality(v_values) then
      raise exception 'Shattered Sigil configuration is incomplete.';
    end if;
    v_from:=(p_action->>'from')::integer; v_to:=(p_action->>'to')::integer;
    if v_from is null or v_to is null
       or v_from<0 or v_to<0 or v_from>=cardinality(v_values) or v_to>=cardinality(v_values) then
      raise exception 'Invalid sigil tile.';
    end if;
    if not (
      (abs(v_from-v_to)=1 and floor(v_from::numeric/v_size)=floor(v_to::numeric/v_size))
      or abs(v_from-v_to)=v_size
    ) then raise exception 'Only adjacent fragments may trade places.'; end if;
    v_tmp:=v_values[v_from+1]; v_values[v_from+1]:=v_values[v_to+1]; v_values[v_to+1]:=v_tmp;
    v_new_state:=jsonb_set(v_state,'{order}',to_jsonb(v_values),true);
    v_new_move_count:=v_new_move_count+1;
    v_solved := v_values = v_target_values;

  elsif v_puzzle.puzzle_type = 'arcane_circuit' then
    if v_action_type <> 'rotate' then raise exception 'Invalid Arcane Circuit action.'; end if;
    select array_agg(value::integer order by ordinality) into v_rotations
      from jsonb_array_elements_text(coalesce(v_state->'rotations','[]'::jsonb)) with ordinality as r(value,ordinality);
    select array_agg(value::integer order by ordinality) into v_masks
      from jsonb_array_elements_text(coalesce(v_puzzle.public_config->'masks','[]'::jsonb)) with ordinality as r(value,ordinality);
    select array_agg(value::integer order by ordinality) into v_target_masks
      from jsonb_array_elements_text(coalesce(v_secret->'target_masks','[]'::jsonb)) with ordinality as r(value,ordinality);
    if cardinality(v_rotations) is null
       or cardinality(v_rotations) <> cardinality(v_masks)
       or cardinality(v_rotations) <> cardinality(v_target_masks) then
      raise exception 'Arcane Circuit configuration is incomplete.';
    end if;
    v_index:=(p_action->>'index')::integer;
    v_delta:=coalesce((p_action->>'delta')::integer,1);
    if v_index<0 or v_index>=cardinality(v_rotations) then raise exception 'Invalid circuit tile.'; end if;
    v_rotations[v_index+1] := ((v_rotations[v_index+1] + v_delta) % 4 + 4) % 4;
    v_new_state:=jsonb_set(v_state,'{rotations}',to_jsonb(v_rotations),true);
    v_new_move_count:=v_new_move_count+1;
    v_solved := true;
    for i in 1..cardinality(v_rotations) loop
      if public.rotate_campaign_puzzle_mask(v_masks[i], v_rotations[i]) <> v_target_masks[i] then
        v_solved := false;
        exit;
      end if;
    end loop;

  elsif v_puzzle.puzzle_type = 'rune_sequence' then
    if v_action_type <> 'sequence_submit' then raise exception 'Invalid Rune Sequence action.'; end if;
    select array_agg(value order by ordinality) into v_solution
      from jsonb_array_elements_text(coalesce(v_secret->'sequence','[]'::jsonb)) with ordinality as s(value,ordinality);
    select array_agg(value order by ordinality) into v_guess
      from jsonb_array_elements_text(coalesce(p_action->'sequence','[]'::jsonb)) with ordinality as g(value,ordinality);
    v_level:=greatest(1,coalesce((v_state->>'level')::integer,1));
    v_base:=greatest(1,coalesce((v_puzzle.public_config->>'base_length')::integer,3));
    v_max_level:=greatest(1,coalesce((v_puzzle.public_config->>'max_level')::integer,5));
    v_needed:=v_base+v_level-1;
    if coalesce(cardinality(v_solution),0) < v_needed then
      raise exception 'Rune Sequence configuration is incomplete.';
    end if;
    v_prefix:=v_solution[1:v_needed];
    if coalesce(cardinality(v_guess),0)<>v_needed then
      raise exception 'The reproduced sequence has the wrong length.';
    end if;
    v_new_move_count:=v_new_move_count+1;
    if v_guess=v_prefix then
      if v_level>=v_max_level then
        v_solved:=true;
        v_new_state:=jsonb_set(v_state,'{last_feedback}',to_jsonb('correct'::text),true);
      else
        v_new_state:=jsonb_set(jsonb_set(v_state,'{level}',to_jsonb(v_level+1),true),'{last_feedback}',to_jsonb('correct'::text),true);
      end if;
    else
      v_new_attempt_count:=v_new_attempt_count+1;
      v_reset_on_miss:=coalesce((v_puzzle.public_config->>'reset_on_miss')::boolean,false);
      v_new_state:=jsonb_set(
        jsonb_set(v_state,'{level}',to_jsonb(case when v_reset_on_miss then 1 else v_level end),true),
        '{last_feedback}',to_jsonb('wrong'::text),true
      );
    end if;
  else
    raise exception 'Unsupported puzzle type.';
  end if;

  if not v_solved then
    if v_puzzle.move_limit is not null and v_new_move_count >= v_puzzle.move_limit then v_failed:=true; end if;
    if v_puzzle.attempt_limit is not null and v_new_attempt_count >= v_puzzle.attempt_limit then v_failed:=true; end if;
  end if;

  v_move_number:=v_new_move_count;
  update public.campaign_puzzle_runs
  set state=v_new_state,
      move_count=v_new_move_count,
      attempt_count=v_new_attempt_count,
      status=case when v_solved then 'solved' when v_failed then 'failed' else 'active' end,
      solved_at=case when v_solved then now() else solved_at end,
      failed_at=case when v_failed then now() else failed_at end,
      controller_user_id=case when v_solved or v_failed then null else controller_user_id end,
      controller_name=case when v_solved or v_failed then null else controller_name end,
      control_expires_at=case when v_solved or v_failed then null else now()+interval '45 seconds' end,
      version=version+1,
      updated_at=now()
  where id=v_run.id;

  insert into public.campaign_puzzle_moves (
    run_id,puzzle_id,campaign_id,actor_id,move_number,action
  ) values (
    v_run.id,v_puzzle.id,v_puzzle.campaign_id,auth.uid(),v_move_number,p_action
  );

  if v_solved then
    update public.campaign_puzzles set status='solved', updated_at=now() where id=v_puzzle.id;
  elsif v_failed then
    update public.campaign_puzzles set status='failed', updated_at=now() where id=v_puzzle.id;
  end if;

  return jsonb_build_object(
    'status',case when v_solved then 'solved' when v_failed then 'failed' else 'active' end,
    'state',v_new_state,
    'move_count',v_new_move_count,
    'attempt_count',v_new_attempt_count,
    'solved',v_solved,
    'failed',v_failed
  );
end;
$$;

-- RPC permissions.
revoke all on function public.save_campaign_puzzle(text,uuid,jsonb) from public;
revoke all on function public.start_campaign_puzzle(uuid,boolean) from public;
revoke all on function public.set_campaign_puzzle_visibility(uuid,boolean) from public;
revoke all on function public.archive_campaign_puzzle(uuid) from public;
revoke all on function public.take_campaign_puzzle_control(uuid) from public;
revoke all on function public.heartbeat_campaign_puzzle_control(uuid) from public;
revoke all on function public.release_campaign_puzzle_control(uuid) from public;
revoke all on function public.expire_campaign_puzzle_run(uuid) from public;
revoke all on function public.reveal_campaign_puzzle_sequence(uuid) from public;
revoke all on function public.apply_campaign_puzzle_action(uuid,jsonb) from public;

grant execute on function public.save_campaign_puzzle(text,uuid,jsonb) to authenticated;
grant execute on function public.start_campaign_puzzle(uuid,boolean) to authenticated;
grant execute on function public.set_campaign_puzzle_visibility(uuid,boolean) to authenticated;
grant execute on function public.archive_campaign_puzzle(uuid) to authenticated;
grant execute on function public.take_campaign_puzzle_control(uuid) to authenticated;
grant execute on function public.heartbeat_campaign_puzzle_control(uuid) to authenticated;
grant execute on function public.release_campaign_puzzle_control(uuid) to authenticated;
grant execute on function public.expire_campaign_puzzle_run(uuid) to authenticated;
grant execute on function public.reveal_campaign_puzzle_sequence(uuid) to authenticated;
grant execute on function public.apply_campaign_puzzle_action(uuid,jsonb) to authenticated;

-- Postgres Changes provides authoritative committed-state synchronization.
do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='campaign_puzzles') then
      alter publication supabase_realtime add table public.campaign_puzzles;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='campaign_puzzle_runs') then
      alter publication supabase_realtime add table public.campaign_puzzle_runs;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='campaign_puzzle_moves') then
      alter publication supabase_realtime add table public.campaign_puzzle_moves;
    end if;
  end if;
end;
$$;

-- Private Broadcast + Presence rooms, scoped to puzzle runs the user may view.
drop policy if exists "Puzzle realtime receive" on realtime.messages;
create policy "Puzzle realtime receive"
on realtime.messages for select to authenticated
using (
  realtime.messages.extension in ('broadcast','presence')
  and public.can_access_campaign_puzzle_topic((select realtime.topic()))
);

drop policy if exists "Puzzle realtime send" on realtime.messages;
create policy "Puzzle realtime send"
on realtime.messages for insert to authenticated
with check (
  realtime.messages.extension in ('broadcast','presence')
  and public.can_access_campaign_puzzle_topic((select realtime.topic()))
);

-- Mark the module available for both existing campaigns without hard-coded UUIDs.
update public.campaigns
set enabled_modules = case
  when 'puzzles' = any(coalesce(enabled_modules,'{}'::text[])) then enabled_modules
  else array_append(coalesce(enabled_modules,'{}'::text[]),'puzzles')
end,
updated_at=now()
where slug in ('nattau','barovia');

commit;

select c.slug, c.enabled_modules
from public.campaigns c
where c.slug in ('nattau','barovia')
order by c.slug;
